name: Build application

on:
  workflow_dispatch:

permissions:
  contents: write
  issues: write
  pull-requests: write

env:
  VERSION: ${{ github.ref_name }}

jobs:
  version:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: "actions/setup-node@v4"
        with:
          node-version: 'lts/*'
      - run: |
          npm install --save-dev semantic-release semantic-release-export-data
      - name: Generate Build ID
        id: build_id
        env:
          GITHUB_TOKEN: ${{ secrets.SEMANTIC_RELEASE }}
        run: npx semantic-release --dry-run

  build:
    needs: version
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            platform: linux
          - os: macos-latest
            platform: macos
          - os: windows-latest
            platform: windows

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pyinstaller

      - name: Build Binary
        run: |
          pyinstaller audio_mfcc.spec
        shell: bash
        env:
          BUILD_ID: ${{ steps.build_id.outputs.new-release-version }}

      - name: Rename Binary with Build ID
        run: |
          if [ "${{ matrix.platform }}" = "windows" ]; then
            mv dist/fmdb_audio_mfcc.exe "dist/fmdb_audio_mfcc-${{ env.BUILD_ID }}.exe"
          else
            mv dist/fmdb_audio_mfcc "dist/fmdb_audio_mfcc-${{ env.BUILD_ID }}"
          fi
        shell: bash

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform }}-fmdb_audio_mfcc
          path: dist/fmdb_audio_mfcc-*

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download Linux Artifact
        uses: actions/download-artifact@v4
        with:
          name: linux-fmdb_audio_mfcc
          path: dist/linux

      - name: Download MacOS Artifact
        uses: actions/download-artifact@v4
        with:
          name: macos-fmdb_audio_mfcc
          path: dist/macos

      - name: Download Windows Artifact
        uses: actions/download-artifact@v4
        with:
          name: windows-fmdb_audio_mfcc
          path: dist/windows

      - name: List Artifacts
        run: |
          ls -R dist/
        shell: bash

      - uses: "actions/setup-node@v4"
        with:
          node-version: 'lts/*'

      - name: "Run semantic-release"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm install --save-dev semantic-release
          npx semantic-release