name: Build application

on:
  workflow_dispatch:

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  version:
    runs-on: ubuntu-24.04
    outputs:
      new-release-version: ${{ steps.build_id.outputs.new-release-version }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: "actions/setup-node@v4"
        with:
          node-version: 'lts/*'
      - run: |
          npm install --save-dev semantic-release semantic-release-export-data
      - name: Generate Build ID
        id: build_id
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release --dry-run

  build:
    needs: version
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            platform: linux
          - os: macos-latest
            platform: macos
          - os: windows-latest
            platform: windows

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pyinstaller

      - name: Create PyInstaller Spec if needed
        run: |
          if [ ! -f audio_features.spec ]; then
            python -m PyInstaller --name=fmdb_audio_features --onefile audio_features/app.py
          fi
        shell: bash

      - name: Build Binary
        run: |
          if [ -f audio_features.spec ]; then
            pyinstaller audio_features.spec
          else
            pyinstaller --name=fmdb_audio_features --onefile audio_features/app.py
          fi
        shell: bash
        env:
          BUILD_ID: ${{ needs.version.outputs.new-release-version }}

      - name: Rename Binary with Build ID
        run: |
          if [ "${{ matrix.platform }}" = "windows" ]; then
            mv dist/fmdb_audio_features.exe "dist/fmdb_audio_features-${{ needs.version.outputs.new-release-version }}.exe"
          else
            mv dist/fmdb_audio_features "dist/fmdb_audio_features-${{ needs.version.outputs.new-release-version }}"
          fi
        shell: bash

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform }}-fmdb_audio_features
          path: dist/fmdb_audio_features-*

  release:
    needs: [version, build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download Linux Artifact
        uses: actions/download-artifact@v4
        with:
          name: linux-fmdb_audio_features
          path: dist/linux

      - name: Download MacOS Artifact
        uses: actions/download-artifact@v4
        with:
          name: macos-fmdb_audio_features
          path: dist/macos

      - name: Download Windows Artifact
        uses: actions/download-artifact@v4
        with:
          name: windows-fmdb_audio_features
          path: dist/windows

      - name: List Artifacts
        run: |
          ls -R dist/
        shell: bash

      - uses: "actions/setup-node@v4"
        with:
          node-version: 'lts/*'

      - name: "Run semantic-release"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm install --save-dev semantic-release
          npx semantic-release