name: Build application

on:
  workflow_dispatch:

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  version:
    runs-on: ubuntu-24.04
    outputs:
      new_release_version: ${{ steps.extract_version.outputs.new_release_version }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          
      - uses: "actions/setup-node@v4"
        with:
          node-version: 'lts/*'
          
      - name: Install Semantic Release
        run: |
          npm install --save-dev semantic-release semantic-release-export-data @semantic-release/git
          
      - name: Generate Build ID
        id: build_id
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Running semantic-release in dry-run mode to determine next version"
          npx semantic-release --dry-run | tee semantic-release-output.txt
          
      - name: Extract Version
        id: extract_version
        run: |
          VERSION=$(grep -o "The next release version is [0-9]\+\.[0-9]\+\.[0-9]\+" semantic-release-output.txt | awk '{print $6}')
          if [ -z "$VERSION" ]; then
            VERSION="0.0.1-dev"
            echo "No new version detected, using default: $VERSION"
          else
            echo "Detected new version: $VERSION"
          fi
          echo "new_release_version=$VERSION" >> $GITHUB_OUTPUT

  build:
    needs: version
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            platform: linux
          - os: macos-latest
            platform: macos
          - os: windows-latest
            platform: windows

    steps:
      - name: Checkout Code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pyinstaller

      - name: Create PyInstaller Spec if needed
        run: |
          if [ ! -f audio_features.spec ]; then
            python -m PyInstaller --name=fmdb_audio_features --onefile audio_features/app.py
          fi
        shell: bash

      - name: Build Binary
        run: |
          echo "Building with version: ${{ needs.version.outputs.new_release_version }}"
          if [ -f audio_features.spec ]; then
            pyinstaller audio_features.spec
          else
            pyinstaller --name=fmdb_audio_features --onefile audio_features/app.py
          fi
        shell: bash
        env:
          BUILD_ID: ${{ needs.version.outputs.new_release_version }}

      - name: Rename Binary with Build ID and Platform
        run: |
          if [ "${{ matrix.platform }}" = "windows" ]; then
            mv dist/fmdb_audio_features.exe "dist/fmdb_audio_features-${{ needs.version.outputs.new_release_version }}-${{ matrix.platform }}.exe"
          else
            mv dist/fmdb_audio_features "dist/fmdb_audio_features-${{ needs.version.outputs.new_release_version }}-${{ matrix.platform }}"
          fi
        shell: bash

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform }}-fmdb_audio_features
          path: dist/fmdb_audio_features-*

  release:
    needs: [version, build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Download Linux Artifact
        uses: actions/download-artifact@v4
        with:
          name: linux-fmdb_audio_features
          path: dist/linux

      - name: Download MacOS Artifact
        uses: actions/download-artifact@v4
        with:
          name: macos-fmdb_audio_features
          path: dist/macos

      - name: Download Windows Artifact
        uses: actions/download-artifact@v4
        with:
          name: windows-fmdb_audio_features
          path: dist/windows

      - name: List Artifacts
        run: |
          ls -R dist/
        shell: bash

      - uses: "actions/setup-node@v4"
        with:
          node-version: 'lts/*'

      - name: "Run semantic-release"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm install --save-dev semantic-release @semantic-release/git
          npx semantic-release